/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.env.types --include-runtime=false --env-interface=WorkerEnv` (hash: d24649f2d6eca6baf2923665905bd594)
interface __BaseEnv_WorkerEnv {
	VM_IMAGE_REGISTRY_BUCKET: R2Bucket;
	VM_RUN_ARTIFACTS_BUCKET: R2Bucket;
	DB: D1Database;
	FLAGS: Flagship;
	ACCESS_INVITE_RATE_LIMITER: RateLimit;
	STARGATE_ADMIN_SERVICE: Fetcher;
	ASSETS: Fetcher;
	BETTER_AUTH_APP_NAME: "intar.dev";
	BETTER_AUTH_URL: "https://intar.dev";
	CONTROL_PLANE_MAINTENANCE: "off";
	LEARNER_RUN_CLI_V1_ENFORCEMENT: "off";
	AGENT_JWT_ISSUER: "intar-agent-bridge";
	AGENT_JWT_AUDIENCE: "agent-connect";
	STARGATE_ROUTE_TTL_SECONDS: "14400";
	STARGATE_ADMIN_AUTH_HEADER: "cf-access-jwt-assertion";
	STARGATE_ADMIN_AUTH_ISSUER: "intar.dev";
	STARGATE_ADMIN_AUTH_AUDIENCE: "stargate-admin";
	ACCESS_INVITE_TOKEN_ENCRYPTION_KEY_V1: string;
	CONTROL_PLANE_MAINTENANCE_BYPASS_SECRET: string;
	STARGATE_EGRESS_IPV4_CIDRS: string;
	HOST_RUNTIME: DurableObjectNamespace<import("./src/worker").HostRuntimeDO>;
	REGISTRY_CLEANUP: Service /* entrypoint RegistryCleanup from intar-dev-image-registry-cleanup */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "HostRuntimeDO";
	}
	interface Env extends __BaseEnv_WorkerEnv {}
}
interface WorkerEnv extends __BaseEnv_WorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_APP_NAME" | "BETTER_AUTH_URL" | "CONTROL_PLANE_MAINTENANCE" | "LEARNER_RUN_CLI_V1_ENFORCEMENT" | "AGENT_JWT_ISSUER" | "AGENT_JWT_AUDIENCE" | "STARGATE_ROUTE_TTL_SECONDS" | "STARGATE_ADMIN_AUTH_HEADER" | "STARGATE_ADMIN_AUTH_ISSUER" | "STARGATE_ADMIN_AUTH_AUDIENCE" | "ACCESS_INVITE_TOKEN_ENCRYPTION_KEY_V1" | "CONTROL_PLANE_MAINTENANCE_BYPASS_SECRET" | "STARGATE_EGRESS_IPV4_CIDRS">> {}
}
