[package]
name = "kino"
version = "0.1.24"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
axum = { workspace = true, features = ["http1", "tokio"] }
base64.workspace = true
clap.workspace = true
hcl-rs.workspace = true
intar-kino-proto = { path = "../intar-kino-proto" }
jsonpath-rust.workspace = true
k8s-openapi.workspace = true
kube.workspace = true
prost.workspace = true
regex.workspace = true
rustls = { workspace = true, features = ["ring"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
tower = { workspace = true, features = ["util"] }

[target.'cfg(target_os = "linux")'.dependencies]
crossterm.workspace = true
pty-process.workspace = true
rustix.workspace = true
signal-hook.workspace = true
tokio-vsock.workspace = true
