self-hosted-runner:
  labels:
    - namespace-profile-intar-dev
paths:
  .github/workflows/workshop-multicloud-flag.yml:
    ignore:
      # GitHub expressions are resolved before the inline shell runs.
      - 'shellcheck reported issue in this script: SC2016:.+'
