/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ea28340ada44775bbe2a0be807eafba6)
interface __BaseEnv_Env {
	PROVIDER_CREDENTIAL_KEK_V1: string;
	HCLOUD_CONNECTIONS: DurableObjectNamespace<import("./src/index").HcloudConnectionDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "HcloudConnectionDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PROVIDER_CREDENTIAL_KEK_V1">> {}
}
