PRAGMA defer_foreign_keys=ON;--> statement-breakpoint
DROP TABLE `gcp_connection_details`;--> statement-breakpoint
DROP TABLE `hetzner_connection_details`;--> statement-breakpoint
DROP TABLE `provider_audit_events`;--> statement-breakpoint
DROP TABLE `provider_connections`;--> statement-breakpoint
DROP TABLE `provider_credential_versions`;--> statement-breakpoint
DROP TABLE `provider_price_line_items`;--> statement-breakpoint
DROP TABLE `provider_price_observations`;--> statement-breakpoint
DROP TABLE `runtime_actual_state`;--> statement-breakpoint
DROP TABLE `runtime_artifact_upload_grants`;--> statement-breakpoint
DROP TABLE `runtime_checkpoint_bundles`;--> statement-breakpoint
DROP TABLE `runtime_guest_credentials`;--> statement-breakpoint
DROP TABLE `runtime_guest_reports`;--> statement-breakpoint
DROP TABLE `runtime_provider_allocations`;--> statement-breakpoint
DROP TABLE `runtime_provider_cost_ledger`;--> statement-breakpoint
DROP TABLE `runtime_provider_operations`;--> statement-breakpoint
DROP TABLE `runtime_provider_reconciliation`;--> statement-breakpoint
DROP TABLE `runtime_provider_resources`;--> statement-breakpoint
DROP TABLE `workshop_assist_grants`;--> statement-breakpoint
DROP TABLE `workshop_events`;--> statement-breakpoint
DROP TABLE `workshop_help_requests`;--> statement-breakpoint
DROP TABLE `workshop_module_progress`;--> statement-breakpoint
DROP TABLE `workshop_publication_checkpoints`;--> statement-breakpoint
DROP TABLE `workshop_publications`;--> statement-breakpoint
DROP TABLE `workshop_registry_tokens`;--> statement-breakpoint
DROP TABLE `workshop_route_issuance_intents`;--> statement-breakpoint
DROP TABLE `workshop_runtime_profile_certifications`;--> statement-breakpoint
DROP TABLE `workshop_runtime_profiles`;--> statement-breakpoint
DROP TABLE `workshop_session_cost_forecast_line_items`;--> statement-breakpoint
DROP TABLE `workshop_session_cost_forecasts`;--> statement-breakpoint
DROP TABLE `workshop_session_cost_summaries`;--> statement-breakpoint
DROP TABLE `workshop_session_members`;--> statement-breakpoint
DROP TABLE `workshop_session_runtime_selections`;--> statement-breakpoint
DROP TABLE `workshop_sessions`;--> statement-breakpoint
DROP TABLE `workshop_template_revisions`;--> statement-breakpoint
DROP TABLE `workshop_templates`;--> statement-breakpoint
DROP TABLE `workshop_workspace_generations`;--> statement-breakpoint
DROP TABLE `workshop_workspaces`;--> statement-breakpoint
ALTER TABLE `member` DROP COLUMN `workshop_access_revoking_at`;--> statement-breakpoint
PRAGMA defer_foreign_keys=OFF;
