[package]
name = "intar-workshop-cli"
version = "0.1.2"
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
intar-workshop-manifest = { path = "../intar-workshop-manifest" }
reqwest = { workspace = true, features = ["blocking", "json", "multipart", "rustls"] }
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
