[package]
name = "intar-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
base16ct.workspace = true
base64.workspace = true
clap.workspace = true
cloud-hypervisor-client = { path = "../cloud-hypervisor-client" }
dirs.workspace = true
fatfs.workspace = true
futures-util.workspace = true
fs2.workspace = true
getrandom.workspace = true
prost.workspace = true
reqwest.workspace = true
rustls.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
time.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
prost-build.workspace = true
protoc-bin-vendored.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
