/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/image-registry-cleanup/wrangler.jsonc --env-file=workers/image-registry-cleanup/.env.types --include-runtime=false --env-interface=CleanupWorkerEnv workers/image-registry-cleanup/worker-configuration.d.ts` (hash: 33a5120fd415b0d9652036e55113fe97)
interface __BaseEnv_CleanupWorkerEnv {
	VM_IMAGE_REGISTRY_BUCKET: R2Bucket;
	DB: D1Database;
	REGISTRY_CLEANUP_MODE: "report-only";
	CONTROL_PLANE: Service /* entrypoint MaintenanceState from intar-dev */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_CleanupWorkerEnv {}
}
interface CleanupWorkerEnv extends __BaseEnv_CleanupWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "REGISTRY_CLEANUP_MODE">> {}
}
