/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5a59a7e6cfc8bf92e431b624debd3633)
interface __BaseEnv_Env {
	HETZNER_PROVIDER_CREDENTIAL_KEK_V1: string;
	HETZNER_CONNECTIONS: DurableObjectNamespace<import("./src/index").HetznerConnectionDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "HetznerConnectionDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "HETZNER_PROVIDER_CREDENTIAL_KEK_V1">> {}
}
