/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bf5f94c2be73740281e9a8cc186c79e8)
interface __BaseEnv_Env {
	GCP_PROVIDER_CREDENTIAL_KEK_V1: string;
	GCP_CATALOG_API_KEY: string;
	GCP_CONNECTIONS: DurableObjectNamespace<import("./src/index").GcpConnectionDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "GcpConnectionDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GCP_PROVIDER_CREDENTIAL_KEK_V1" | "GCP_CATALOG_API_KEY">> {}
}
