use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum SessionKind {
    NativeSsh,
    BrowserTerminal,
    WorkspaceApp,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum TerminalSessionMode {
    Browser,
    Native,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum NativeTerminalAuthMode {
    ProfileKeys,
}

#[derive(Clone, Debug, Default, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub struct RouteMetadata {
    pub host_id: Option<String>,
    pub run_id: Option<String>,
    pub vm_id: Option<String>,
    pub user_id: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub struct IssueTerminalSessionRequest {
    pub route_username: String,
    pub target_username: String,
    pub target_ip: String,
    pub target_port: u16,
    pub target_host_key_openssh: String,
    pub target_private_key_openssh: String,
    #[serde(default)]
    pub authorized_client_public_keys_openssh: Vec<String>,
    pub route_expires_at: i64,
    pub mode: TerminalSessionMode,
    #[serde(default)]
    pub metadata: RouteMetadata,
}

#[derive(Clone, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub struct BrowserTerminalSession {
    pub websocket_url: String,
}

#[derive(Clone, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub struct NativeTerminalSession {
    pub auth_mode: NativeTerminalAuthMode,
    pub authorized_key_count: usize,
    pub ssh_host: String,
    pub ssh_port: u16,
    pub username: String,
    pub public_host_key_openssh: String,
    pub public_host_key_fingerprint_sha256: String,
    pub known_hosts_line: String,
    pub command: String,
}

#[derive(Clone, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub struct IssueTerminalSessionResponse {
    pub route_username: String,
    pub expires_at: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub browser: Option<BrowserTerminalSession>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub native: Option<NativeTerminalSession>,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum WorkspaceAppProtocol {
    Http,
}

#[derive(Clone, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub struct IssueWorkspaceAppSessionRequest {
    /// Random, human-readable identifier generated by the control plane. It
    /// is a public route identity, not an authorization secret, and must not
    /// contain user-provided labels or resource names.
    pub route_id: String,
    /// Refuse to replace an existing route with this identifier.
    #[serde(default)]
    pub create_only: bool,
    pub target_username: String,
    /// Literal IP and port of the guest SSH endpoint already exposed to
    /// Stargate by the VM harness.
    pub target_ip: String,
    pub target_ssh_port: u16,
    pub target_host_key_openssh: String,
    pub target_private_key_openssh: String,
    /// Allowlisted application port inside the guest. Stargate reaches it
    /// through an SSH direct-tcpip channel; it is never published on the host.
    pub target_app_port: u16,
    pub protocol: WorkspaceAppProtocol,
    /// Optional virtual-host value sent only to the declared guest service.
    /// The public route hostname remains available as X-Forwarded-Host.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upstream_host: Option<String>,
    pub route_expires_at: i64,
    #[serde(default)]
    pub metadata: RouteMetadata,
}

#[derive(Clone, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub struct IssueWorkspaceAppSessionResponse {
    pub route_id: String,
    /// URL containing a short-lived, single-use bootstrap capability. The
    /// public gateway exchanges it for a route-bound browser session and
    /// redirects to the same URL without the capability.
    pub url: String,
    pub bootstrap_expires_at: i64,
    pub expires_at: i64,
}
