#!/usr/bin/env bun

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const repositoryRoot = resolve(import.meta.dir, "..");
const output = resolve(
  repositoryRoot,
  "apps/web/src/generated/scenario-authoring-config.ts",
);

const baseImagesHcl = readFileSync(
  resolve(repositoryRoot, "content/scenarios/base-images.hcl"),
  "utf8",
);
const generated = `// Generated by tools/generate-scenario-authoring-config.ts. Do not edit.\n` +
  `export const baseImagesHcl = ${JSON.stringify(baseImagesHcl)};\n`;

writeFileSync(output, generated);
