/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerEnv` (hash: 76e978745502b5ab778d27a60f95eb97)
interface __BaseEnv_WorkerEnv {
	VM_IMAGE_REGISTRY_BUCKET: R2Bucket;
	VM_RUN_ARTIFACTS_BUCKET: R2Bucket;
	DB: D1Database;
	ACCESS_REQUEST_RATE_LIMITER: RateLimit;
	STARGATE_ADMIN_SERVICE: Fetcher;
	ASSETS: Fetcher;
	BETTER_AUTH_APP_NAME: "intar.dev";
	AGENT_JWT_ISSUER: "intar-agent-bridge";
	AGENT_JWT_AUDIENCE: "agent-connect";
	STARGATE_ROUTE_TTL_SECONDS: "14400";
	STARGATE_ADMIN_AUTH_HEADER: "cf-access-jwt-assertion";
	STARGATE_ADMIN_AUTH_ISSUER: "intar.dev";
	STARGATE_ADMIN_AUTH_AUDIENCE: "stargate-admin";
	BETTER_AUTH_URL: string;
	HOST_RUNTIME: DurableObjectNamespace<import("./src/worker").HostRuntimeDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "HostRuntimeDO";
	}
	interface Env extends __BaseEnv_WorkerEnv {}
}
interface WorkerEnv extends __BaseEnv_WorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_APP_NAME" | "AGENT_JWT_ISSUER" | "AGENT_JWT_AUDIENCE" | "STARGATE_ROUTE_TTL_SECONDS" | "STARGATE_ADMIN_AUTH_HEADER" | "STARGATE_ADMIN_AUTH_ISSUER" | "STARGATE_ADMIN_AUTH_AUDIENCE" | "BETTER_AUTH_URL">> {}
}
