[package]
name = "intar-agent"
version = "0.2.3"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
axum = { workspace = true, features = ["http1", "json", "macros", "tokio", "ws"] }
base16ct.workspace = true
base64.workspace = true
clap.workspace = true
cloud-hypervisor-client = { path = "../cloud-hypervisor-client" }
dirs.workspace = true
fatfs.workspace = true
futures-util.workspace = true
fs2.workspace = true
getrandom.workspace = true
intar-contracts = { path = "../intar-contracts" }
intar-kino-proto = { path = "../intar-kino-proto" }
prost.workspace = true
reqwest = { workspace = true, features = ["json", "rustls-no-provider", "stream"] }
rustls = { workspace = true, features = ["ring", "std", "tls12"] }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
time.workspace = true
tokio.workspace = true
tokio-tungstenite = { workspace = true, features = ["connect", "rustls-tls-webpki-roots"] }
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zstd.workspace = true

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]

[lints]
workspace = true
