import type { DesiredGuestToolsV1 } from "@/generated/bridge";
import { isRecord, normalizeSha256 } from "@/control-plane/image-registry/shared";

export type ScenarioGuestToolsChannel = "stable" | "candidate";

type ScenarioGuestToolsPinSource = ScenarioGuestToolsChannel | "static";

/**
 * Required Worker variable that carries the verified cutover release pin.
 *
 * The value is generated by tools/deploy/guest-tools-pin.ts from measured
 * release objects, and the deploy injects it into the generated config. There
 * is no fallback to the dynamic R2 channel: a Worker without this variable is
 * a misconfigured ABI 2 release and fails closed.
 */
export const SCENARIO_GUEST_TOOLS_STATIC_PIN_ENV =
  "SCENARIO_GUEST_TOOLS_STATIC_PIN_JSON";

const TOOLS_DISK_SIZE_BYTES = 64 * 1024 * 1024;

const PIN_KEYS = [
  "schema_version",
  "bootstrap_abi",
  "tools_disk_sha256",
  "tools_disk_size_bytes",
  "compressed_disk_sha256",
  "compressed_disk_size_bytes",
  "kino_sha256",
  "kino_size_bytes",
] as const;

export interface ScenarioGuestToolsPinV1 {
  schema_version: 1;
  bootstrap_abi: 2;
  tools_disk_sha256: string;
  tools_disk_size_bytes: number;
  compressed_disk_sha256: string;
  compressed_disk_size_bytes: number;
  kino_sha256: string;
  kino_size_bytes: number;
}

export function scenarioGuestToolsPinKey(
  channel: ScenarioGuestToolsChannel,
): string {
  return "guest-tools/scenario/" + channel + ".json";
}

export function scenarioToolsDiskObjectKey(toolsDiskSha256: string): string {
  return "guest-tools/scenario/disks/" + toolsDiskSha256 + ".ext4.zst";
}

export function scenarioKinoObjectKey(kinoSha256: string): string {
  return "guest-tools/scenario/kino/" + kinoSha256 + "/kino";
}

/**
 * Read the required static pin. Every runtime path uses this function.
 */
export function readScenarioGuestToolsStaticPin(
  env: Cloudflare.Env,
): ScenarioGuestToolsPinV1 {
  const raw = env[SCENARIO_GUEST_TOOLS_STATIC_PIN_ENV];
  if (typeof raw !== "string" || raw.trim().length === 0) {
    throw new Error(
      SCENARIO_GUEST_TOOLS_STATIC_PIN_ENV +
        " is not configured: deploy the verified ABI 2 release pin before this Worker",
    );
  }
  let value: unknown;
  try {
    value = JSON.parse(raw);
  } catch {
    throw new Error(SCENARIO_GUEST_TOOLS_STATIC_PIN_ENV + " is not valid JSON");
  }
  return parseScenarioGuestToolsPin(value, "static");
}

export function loadScenarioGuestToolsPin(
  env: Cloudflare.Env,
): DesiredGuestToolsV1 {
  return desiredGuestTools(readScenarioGuestToolsStaticPin(env));
}

/**
 * Read the dynamic publish channel pin. This is the host publish pipeline
 * only; no runtime path calls it.
 */
export async function loadPublishedScenarioGuestToolsPin(
  env: Cloudflare.Env,
  channel: ScenarioGuestToolsChannel,
): Promise<DesiredGuestToolsV1> {
  const object = await env.VM_IMAGE_REGISTRY_BUCKET.get(
    scenarioGuestToolsPinKey(channel),
  );
  if (!object) {
    throw new Error("scenario guest-tools " + channel + " pin is unavailable");
  }
  let value: unknown;
  try {
    value = await object.json();
  } catch {
    throw new Error("scenario guest-tools " + channel + " pin is invalid JSON");
  }
  const pin = parseScenarioGuestToolsPin(value, channel);
  await verifyScenarioGuestToolsObjects(env, pin, channel);
  return desiredGuestTools(pin);
}

export function parseScenarioGuestToolsPin(
  value: unknown,
  source: ScenarioGuestToolsPinSource,
): ScenarioGuestToolsPinV1 {
  const invalid = (detail: string): Error =>
    new Error("scenario guest-tools " + source + " pin is invalid: " + detail);
  if (!isRecord(value)) {
    throw invalid("it is not an object");
  }
  const unknownKeys = Object.keys(value).filter(
    (key) => !(PIN_KEYS as readonly string[]).includes(key),
  );
  if (unknownKeys.length > 0) {
    throw invalid("unknown keys " + unknownKeys.sort().join(", "));
  }
  const toolsDiskSha256 = normalizeSha256(String(value.tools_disk_sha256 ?? ""));
  const kinoSha256 = normalizeSha256(String(value.kino_sha256 ?? ""));
  const compressedDiskSha256 = normalizeSha256(
    String(value.compressed_disk_sha256 ?? ""),
  );
  if (value.schema_version !== 1) {
    throw invalid(
      "schema_version must be 1, got " + String(value.schema_version),
    );
  }
  if (value.bootstrap_abi !== 2) {
    throw invalid("bootstrap_abi must be 2, got " + String(value.bootstrap_abi));
  }
  if (!toolsDiskSha256 || !compressedDiskSha256 || !kinoSha256) {
    throw invalid("every digest must be 64 lowercase hexadecimal characters");
  }
  if (value.tools_disk_size_bytes !== TOOLS_DISK_SIZE_BYTES) {
    throw invalid(
      "tools_disk_size_bytes must be " +
        TOOLS_DISK_SIZE_BYTES +
        ", got " +
        String(value.tools_disk_size_bytes),
    );
  }
  if (
    typeof value.compressed_disk_size_bytes !== "number" ||
    !Number.isSafeInteger(value.compressed_disk_size_bytes) ||
    value.compressed_disk_size_bytes <= 0
  ) {
    throw invalid("compressed_disk_size_bytes must be a positive integer");
  }
  if (
    typeof value.kino_size_bytes !== "number" ||
    !Number.isSafeInteger(value.kino_size_bytes) ||
    value.kino_size_bytes <= 0
  ) {
    throw invalid("kino_size_bytes must be a positive integer");
  }

  return {
    schema_version: 1,
    bootstrap_abi: 2,
    tools_disk_sha256: toolsDiskSha256,
    tools_disk_size_bytes: TOOLS_DISK_SIZE_BYTES,
    compressed_disk_sha256: compressedDiskSha256,
    compressed_disk_size_bytes: value.compressed_disk_size_bytes,
    kino_sha256: kinoSha256,
    kino_size_bytes: value.kino_size_bytes,
  };
}

export function desiredGuestTools(
  pin: ScenarioGuestToolsPinV1,
): DesiredGuestToolsV1 {
  return {
    tools_disk_sha256: pin.tools_disk_sha256,
    tools_disk_size_bytes: pin.tools_disk_size_bytes,
    kino_sha256: pin.kino_sha256,
    bootstrap_abi: pin.bootstrap_abi,
  };
}

export async function verifyScenarioGuestToolsObjects(
  env: Cloudflare.Env,
  pin: ScenarioGuestToolsPinV1,
  channel: ScenarioGuestToolsChannel,
): Promise<void> {
  const [disk, kino] = await Promise.all([
    env.VM_IMAGE_REGISTRY_BUCKET.head(
      scenarioToolsDiskObjectKey(pin.tools_disk_sha256),
    ),
    env.VM_IMAGE_REGISTRY_BUCKET.head(scenarioKinoObjectKey(pin.kino_sha256)),
  ]);
  if (
    !disk ||
    disk.size !== pin.compressed_disk_size_bytes ||
    !kino ||
    kino.size !== pin.kino_size_bytes
  ) {
    throw new Error("scenario guest-tools " + channel + " objects are unavailable");
  }
}
